
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/RangelReale/osin"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "8.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/felipeweb/osin-mysql"

[[constraint]]
  branch = "master"
  name = "github.com/frustra/bbcode"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/contrib"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/johnniedoe/contrib"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  branch = "master"
  name = "github.com/nfnt/resize"

[[constraint]]
  name = "github.com/osuripple/cheesegull"
  branch = "master"

[[constraint]]
  name = "github.com/pariz/gountries"
  version = "0.1.3"

[[constraint]]
  name = "github.com/pquerna/otp"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/goagain"

[[constraint]]
  branch = "master"
  name = "github.com/rjeczalik/notify"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/thehowl/cieca"

[[constraint]]
  name = "github.com/thehowl/conf"
  version = "0.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/thehowl/qsql"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/mailgun/mailgun-go.v1"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/redis.v5"
  version = "5.2.9"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "zxq.co/ripple/go-discord-oauth"

[[constraint]]
  branch = "master"
  name = "zxq.co/ripple/playstyle"

[[constraint]]
  name = "zxq.co/ripple/rippleapi"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "zxq.co/ripple/schiavolib"

[[constraint]]
  branch = "master"
  name = "zxq.co/x/rs"

[[constraint]]
  branch = "master"
  name = "zxq.co/ripple/agplwarning"
